# -*- coding: utf-8 -*-
from pathlib import Path
from html import escape
import json
out=Path(__file__).resolve().parents[1]
comparisons=[
('activity-main','活动：先看到需要你处理的事','固定导航；待处理原因常驻首屏；运行任务先显示 3 项，可展开全部。'),
('activity-warning','异常：显示原因和下一步','有旧用量缓存时，也优先显示当前错误；数据问题进入相关设置，用量失败提供重试。'),
('notes-main','便签：统一入口，保留编辑区域','导航位置与其他工作空间一致；单项删除使用统一撤销提示。'),
('schedule-edit','日程：编辑区自动出现到眼前','新增和编辑采用同一位置；日期明确；重复规则直接可见；时长支持输入。'),
('schedule-routine-daily','例行事项：表单移到列表前','打开编辑后滚动到表单；不用到列表最底部找保存和取消。'),
('schedule-running','专注：切换工作空间，计时继续','顶部保留持续状态条；点击可展开大倒计时，再返回日程列表。'),
('settings-voice','语音：音量容易找到，配置按需展开','提醒开关和预览先展示；文案、录音、文件等详细设置在对应提醒内展开。'),
('settings-general','通用：常用设置与低频说明分组','明确自动保存；只留一个返回入口；演示与数据来源集中收纳。')]
sections=[]
for key,title,desc in comparisons:
 before=f'../ui-atlas-2026-09-14/screenshots/{key}.png'
 after=f'screenshots/{key}.png'
 assert (out/before).exists() and (out/after).exists(), key
 sections.append(f'''<section id="{key}"><div class="section-head"><h2>{escape(title)}</h2><p>{escape(desc)}</p></div><div class="pair"><figure><figcaption>修改前</figcaption><a href="{before}" target="_blank"><img src="{before}" alt="修改前：{escape(title)}" loading="lazy"></a></figure><figure><figcaption class="after">修改后</figcaption><a href="{after}" target="_blank"><img src="{after}" alt="修改后：{escape(title)}" loading="lazy"></a></figure></div></section>''')
nav=''.join(f'<a href="#{key}">{escape(title.split("：")[0])}</a>' for key,title,_ in comparisons)
gallery=''.join(f'<a class="thumb" href="screenshots/{p.name}" target="_blank"><img src="screenshots/{p.name}" alt="{escape(p.stem)}" loading="lazy"><span>{escape(p.stem)}</span></a>' for p in sorted((out/'screenshots').glob('*.png')))
html='''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Halofold · UI 升级验收</title><style>
:root{color-scheme:dark;font-family:-apple-system,BlinkMacSystemFont,"PingFang SC",sans-serif;background:#111416;color:#eef1f4}*{box-sizing:border-box}body{margin:0}main{max-width:1200px;margin:auto;padding:44px 24px 80px}h1{font-size:32px;margin:14px 0}h2{font-size:21px;margin:0 0 12px}p{color:#abb5bf;line-height:1.75;margin:0}a{color:#8ac4ff;text-decoration:none}a:hover{text-decoration:underline}header>p{max-width:760px}.eyebrow{font-size:12px;letter-spacing:2px;color:#7fbfff}.status{display:flex;gap:10px;flex-wrap:wrap;margin:22px 0}.status span{padding:8px 12px;border:1px solid #30413c;border-radius:7px;color:#a6dab9;font-size:13px}nav{position:sticky;top:0;z-index:1;background:#111416ed;backdrop-filter:blur(10px);border-bottom:1px solid #30353a;padding:14px 0;display:flex;gap:8px;flex-wrap:wrap}nav a{padding:7px 11px;border-radius:7px;background:#20272e;color:#d7e7f7;font-size:13px}section{scroll-margin-top:100px;margin-top:42px}.section-head{margin-bottom:18px}.pair{display:grid;grid-template-columns:1fr 1fr;gap:20px}figure{margin:0;background:#080909;border:1px solid #2d3338;border-radius:14px;overflow:hidden}figcaption{padding:12px 18px;color:#a9b0b8;font-size:13px;background:#191d21;border-bottom:1px solid #2d3338}figcaption.after{color:#8ac4ff}img{display:block;width:100%;height:auto}table{width:100%;border-collapse:collapse;font-size:14px}th,td{text-align:left;padding:14px;border-bottom:1px solid #333a40;line-height:1.6}th{color:#8ac4ff}td:first-child{width:25%}.proof{max-width:620px;margin:20px auto}.gallery{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.thumb{border:1px solid #333a40;border-radius:10px;overflow:hidden;background:#080909;font-size:11px}.thumb span{display:block;padding:10px;word-break:break-word}footer{margin-top:40px;border-top:1px solid #333a40;padding-top:20px;font-size:13px}@media(max-width:760px){main{padding:26px 16px}.pair{grid-template-columns:1fr}.gallery{grid-template-columns:repeat(2,1fr)}h1{font-size:26px}}
</style><main><header><div class="eyebrow">HALOFOLD / 本地实现 / 2026.09.14</div><h1>让操作顺起来，再统一视觉</h1><p>这一版保留深色、紧凑的原生面板。重点处理草稿丢失、待处理信息被挤下去、异常原因不明确，以及导航位置随页面变化的问题。</p><div class="status"><span>原生界面截图</span><span>71 / 71 完整配置测试</span><span>68 / 68 正式功能配置测试</span><span>Xcode 构建通过</span></div><p>这是本地代码与独立演示窗口的验收页，尚未替换日常使用的已安装版本。截图使用隔离的测试数据；窗口居中便于对照。</p></header><nav>'''+nav+'''<a href="#checks">行为验收</a><a href="#gallery">全部新截图</a></nav>'''+''.join(sections)+'''<section id="checks"><h2>行为验收</h2><table><thead><tr><th>检查对象</th><th>结果与证据</th></tr></thead><tbody><tr><td>草稿跨空间、设置返回</td><td>原生窗口已复现：标题“验收草稿：切换后继续编辑”和 45 分钟时长保留，保存前不会创建记录。测试输入通过原生可访问性接口写入。</td></tr><tr><td>隐藏页面</td><td>原生辅助功能树只保留当前工作空间；隐藏的便签编辑器和活动按钮不再混入日程页。</td></tr><tr><td>单项删除与恢复</td><td>便签、日程、自定义例行事项共用 8 秒撤销提示。回归测试验证富文本、ID、时间信息、专注记录，以及删除后的其他新增内容。</td></tr><tr><td>重复日程</td><td>删除本次可撤销；删除后续先展示起始日期和范围。编辑本次不会误改整组重复规则。</td></tr><tr><td>默认时间</td><td>今天使用下一个五分钟刻度；其他日期使用 09:00。跨午夜会连同日期一起前进，已覆盖测试。</td></tr><tr><td>运行状态与导航</td><td>各工作空间保留同一专注状态条。导航不会调用暂停、完成或重新开始；点击可打开详细计时。</td></tr><tr><td>构建与回归</td><td>完整配置 71 项、正式功能配置 68 项测试通过；Xcode Debug 构建通过。正式功能配置排除 3 项仅适用于实验性待办提取功能的测试。</td></tr></tbody></table><figure class="proof"><figcaption>进入设置再返回，未提交的标题和 45 分钟时长仍在</figcaption><img src="screenshots/draft-after-settings.png" alt="草稿在设置返回后保留"></figure></section><section id="gallery"><h2>本轮原生截图</h2><p>点击图片查看原图。滚动内容按当前截图位置展示；不把一张静态图当作完整交互验证。</p><div class="gallery">'''+gallery+'''</div></section><footer><p>验证范围：本机原生视图、隔离数据、模型回归、Debug 编译。尚未验证正式安装包的签名发布、真实刘海位置、多显示器、长时间后台功耗、锁屏后提醒和实际音频输出。修改前截图保留原采集时间，因此示例时刻会与修改后不同。</p><p><a href="README.md">实现与验收记录</a> · <a href="../ui-atlas-2026-09-14/index.html">原 UI 全景册</a></p></footer></main></html>'''
(out/'index.html').write_text(html)
print(out/'index.html')
